name: ec-3.8
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.3
  - autopep8=1.5.3
  - flake8=3.8.3
  - pydocstyle=4.0.1
  - pylint=2.5.2
  - mypy=0.782
  - bpython=0.19
  - qt=5.9.7
  - pyqt=5.9.2
  - matplotlib=3.1.3
  - pip=20.0.2
  - requests=2.23.0
  - urllib3=1.25.8
  - python-dateutil=2.8.1
  - pytz=2020.1
  - tzlocal=2.0.0
  - beautifulsoup4=4.9.1
  - pip:
    - matplot-fmt-pi==2.0.4
